# Generated by Django 6.0.5 on 2026-06-05 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstins', '0003_gstintaxpayerprofile'),
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['assigned_to', 'status'], name='notices_assigne_d4b7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['due_date'], name='notices_due_dat_949dc2_idx'),
        ),
    ]
