# Generated by Codex on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0002_notice_assigned_to_notice_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="provider",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="notice",
            name="provider_reference_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="notice",
            name="provider_notice_type",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="notice",
            name="provider_status",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="notice",
            name="provider_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="provider_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notice",
            name="provider_detail_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notice",
            name="provider_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="provider_detail_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="provider_last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(fields=["provider", "provider_reference_id"], name="notices_provide_0495ac_idx"),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(fields=["provider_synced_at"], name="notices_provide_3e7cab_idx"),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(fields=["provider_detail_synced_at"], name="notices_provide_bd00ae_idx"),
        ),
    ]
