# Generated by Django 6.0.5 on 2026-08-30 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstins', '0004_allow_same_gstin_across_workspaces'),
        ('notices', '0003_notice_provider_sync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeSyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider', models.CharField(default='whitebooks', max_length=32)),
                ('event_type', models.CharField(choices=[('list_sync', 'List sync'), ('detail_fetch', 'Detail fetch'), ('follow_up', 'Follow-up')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=32)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('provider_reference_id', models.CharField(blank=True, max_length=128)),
                ('message', models.TextField(blank=True)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_sync_events', to='gstins.gstin')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_sync_events_initiated', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_events', to='notices.notice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notice_sync_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gstin', 'event_type'], name='notice_sync_gstin_i_c65b19_idx'), models.Index(fields=['notice', 'event_type'], name='notice_sync_notice__10b16d_idx'), models.Index(fields=['provider', 'status'], name='notice_sync_provide_8865de_idx'), models.Index(fields=['created_at'], name='notice_sync_created_0cb68d_idx')],
            },
        ),
    ]
