# Generated by Django 6.0.5 on 2026-05-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('reviewer', 'Reviewer'), ('filer', 'Filer'), ('senior_ca', 'Senior CA'), ('viewer', 'Viewer')], max_length=32),
        ),
    ]
