# Generated by Django 6.0.5 on 2026-06-03 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0002_remove_approvalrequest_approval_re_return__7b4b95_idx_and_more'),
        ('clients', '0001_initial'),
        ('compliance_periods', '0002_complianceperiod_is_locked_and_more'),
        ('gstins', '0001_initial'),
        ('returns', '0002_returnpreparation_approved_by_returnpreparation_arn_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnFiling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider', models.CharField(choices=[('whitebooks', 'WhiteBooks')], default='whitebooks', max_length=32)),
                ('return_type', models.CharField(choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready For Review'), ('approved', 'Approved'), ('queued_for_filing', 'Queued For Filing'), ('submitted', 'Submitted'), ('arn_received', 'ARN Received'), ('filed', 'Filed'), ('failed', 'Failed'), ('needs_retry', 'Needs Retry'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('prepared_snapshot_version', models.PositiveIntegerField(default=1)),
                ('provider_reference_id', models.CharField(blank=True, max_length=128)),
                ('provider_acknowledgement_id', models.CharField(blank=True, max_length=128)),
                ('arn', models.CharField(blank=True, max_length=64)),
                ('readiness_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('arn_received_at', models.DateTimeField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_sync_at', models.DateTimeField(blank=True, null=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_filings', to='approvals.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filings_approved', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_filings', to='clients.client')),
                ('compliance_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_filings', to='compliance_periods.complianceperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filings_filed', to=settings.AUTH_USER_MODEL)),
                ('gstin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_filings', to='gstins.gstin')),
                ('prepared_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='returns.returnpreparation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_filings', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'return_filings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnFilingAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('in_progress', 'In Progress'), ('submitted_to_provider', 'Submitted To Provider'), ('awaiting_status', 'Awaiting Status'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=32)),
                ('provider_request_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('request_payload_hash', models.CharField(blank=True, max_length=128)),
                ('request_summary', models.JSONField(blank=True, default=dict)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('provider_status_raw', models.JSONField(blank=True, default=dict)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('return_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='filings.returnfiling')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filing_attempts_triggered', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'return_filing_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnFilingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('old_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filing_events', to=settings.AUTH_USER_MODEL)),
                ('filing_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='filings.returnfilingattempt')),
                ('return_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='filings.returnfiling')),
            ],
            options={
                'db_table': 'return_filing_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returnfiling',
            index=models.Index(fields=['workspace', 'status'], name='return_fili_workspa_22d71a_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfiling',
            index=models.Index(fields=['client', 'status'], name='return_fili_client__62ced3_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfiling',
            index=models.Index(fields=['gstin', 'status'], name='return_fili_gstin_i_fc6adc_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfiling',
            index=models.Index(fields=['compliance_period', 'status'], name='return_fili_complia_9b46f1_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfiling',
            index=models.Index(fields=['provider', 'status'], name='return_fili_provide_583a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfiling',
            index=models.Index(fields=['arn'], name='return_fili_arn_e889d0_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfiling',
            index=models.Index(fields=['provider_reference_id'], name='return_fili_provide_82b651_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnfiling',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('prepared_return', 'prepared_snapshot_version'), name='unique_active_filing_per_snapshot'),
        ),
        migrations.AddIndex(
            model_name='returnfilingattempt',
            index=models.Index(fields=['return_filing', 'attempt_number'], name='return_fili_return__22995d_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingattempt',
            index=models.Index(fields=['status'], name='return_fili_status_11678d_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingattempt',
            index=models.Index(fields=['provider_request_id'], name='return_fili_provide_32d29b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingattempt',
            index=models.Index(fields=['started_at'], name='return_fili_started_b41bed_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingattempt',
            index=models.Index(fields=['completed_at'], name='return_fili_complet_093edd_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnfilingattempt',
            constraint=models.UniqueConstraint(fields=('return_filing', 'attempt_number'), name='unique_attempt_number_per_filing'),
        ),
        migrations.AddIndex(
            model_name='returnfilingevent',
            index=models.Index(fields=['return_filing', 'created_at'], name='return_fili_return__4fdb56_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingevent',
            index=models.Index(fields=['filing_attempt', 'created_at'], name='return_fili_filing__d97e69_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingevent',
            index=models.Index(fields=['event_type', 'created_at'], name='return_fili_event_t_db57de_idx'),
        ),
    ]
