# Generated by Django 6.0.5 on 2026-06-03 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('filings', '0001_initial'),
        ('gstins', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteBooksAuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider', models.CharField(choices=[('whitebooks', 'WhiteBooks')], default='whitebooks', max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('txn', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('created', 'Created'), ('otp_requested', 'OTP Requested'), ('auth_token_received', 'Auth Token Received'), ('session_active', 'Session Active'), ('failed', 'Failed')], default='created', max_length=32)),
                ('otp_request_payload', models.JSONField(blank=True, default=dict)),
                ('auth_token_payload', models.JSONField(blank=True, default=dict)),
                ('session_metadata', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('response_contract_confirmed', models.BooleanField(default=False)),
                ('last_requested_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitebooks_auth_sessions', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gstin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitebooks_auth_sessions', to='gstins.gstin')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitebooks_auth_sessions_initiated', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitebooks_auth_sessions_verified', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitebooks_auth_sessions', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'whitebooks_auth_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='whitebooks__workspa_b94670_idx'), models.Index(fields=['client', 'status'], name='whitebooks__client__fa2e1c_idx'), models.Index(fields=['gstin', 'status'], name='whitebooks__gstin_i_09da79_idx'), models.Index(fields=['provider', 'status'], name='whitebooks__provide_33506b_idx'), models.Index(fields=['email'], name='whitebooks__email_8e9019_idx'), models.Index(fields=['txn'], name='whitebooks__txn_37db63_idx')],
            },
        ),
    ]
