# Generated by Django 6.0.5 on 2026-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0002_whitebooksauthsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnfiling',
            name='provider',
            field=models.CharField(choices=[('whitebooks', 'WhiteBooks'), ('demo_gsp', 'Demo GSP')], default='whitebooks', max_length=32),
        ),
        migrations.AlterField(
            model_name='whitebooksauthsession',
            name='provider',
            field=models.CharField(choices=[('whitebooks', 'WhiteBooks'), ('demo_gsp', 'Demo GSP')], default='whitebooks', max_length=32),
        ),
    ]
