# Generated by Django 6.0.5 on 2026-06-03 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0003_alter_returnfiling_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnFilingOffset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('applied', 'Applied'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='draft', max_length=32)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('liability_snapshot', models.JSONField(blank=True, default=dict)),
                ('ledger_snapshot', models.JSONField(blank=True, default=dict)),
                ('allocation_summary', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filing_offsets_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('filing_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offset_profiles', to='filings.returnfilingattempt')),
                ('return_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_profiles', to='filings.returnfiling')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'return_filing_offsets',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnFilingOffsetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('source_ledger_type', models.CharField(choices=[('liability', 'Liability'), ('credit', 'Credit'), ('cash', 'Cash')], default='liability', max_length=32)),
                ('source_ledger_id', models.CharField(blank=True, max_length=128)),
                ('liability_ledger_id', models.CharField(blank=True, max_length=128)),
                ('tax_head', models.CharField(choices=[('igst', 'IGST'), ('cgst', 'CGST'), ('sgst', 'SGST'), ('cess', 'CESS'), ('interest', 'Interest'), ('late_fee', 'Late Fee')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('offset_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='filings.returnfilingoffset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'return_filing_offset_lines',
                'ordering': ['line_number', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returnfilingoffset',
            index=models.Index(fields=['return_filing', 'status'], name='return_fili_return__320153_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingoffset',
            index=models.Index(fields=['filing_attempt', 'status'], name='return_fili_filing__38ca76_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingoffset',
            index=models.Index(fields=['status', 'confirmed_at'], name='return_fili_status_67237e_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnfilingoffset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('return_filing', 'version'), name='unique_active_offset_version_per_filing'),
        ),
        migrations.AddIndex(
            model_name='returnfilingoffsetline',
            index=models.Index(fields=['offset_profile', 'tax_head'], name='return_fili_offset__538074_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingoffsetline',
            index=models.Index(fields=['source_ledger_type', 'tax_head'], name='return_fili_source__23e2eb_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingoffsetline',
            index=models.Index(fields=['source_ledger_id'], name='return_fili_source__eee32a_idx'),
        ),
        migrations.AddIndex(
            model_name='returnfilingoffsetline',
            index=models.Index(fields=['liability_ledger_id'], name='return_fili_liabili_e77638_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnfilingoffsetline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('offset_profile', 'line_number'), name='unique_active_offset_line_number_per_profile'),
        ),
    ]
