# Generated by Django 6.0.5 on 2026-06-03 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('filings', '0004_returnfilingoffset_returnfilingoffsetline_and_more'),
        ('gstins', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRolloutPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider', models.CharField(choices=[('whitebooks', 'WhiteBooks'), ('demo_gsp', 'Demo GSP')], default='whitebooks', max_length=32)),
                ('return_type', models.CharField(blank=True, choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B')], max_length=32)),
                ('enable_live_submission', models.BooleanField(default=False)),
                ('enable_live_status_sync', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_rollout_policies', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gstin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_rollout_policies', to='gstins.gstin')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_rollout_policies', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'provider_rollout_policies',
                'ordering': ['workspace_id', 'provider', '-created_at'],
                'indexes': [models.Index(fields=['workspace', 'provider', 'is_active'], name='provider_ro_workspa_62861d_idx'), models.Index(fields=['client', 'provider', 'is_active'], name='provider_ro_client__26fe56_idx'), models.Index(fields=['gstin', 'provider', 'is_active'], name='provider_ro_gstin_i_050b1f_idx'), models.Index(fields=['provider', 'return_type', 'is_active'], name='provider_ro_provide_2dc7ca_idx'), models.Index(fields=['effective_from', 'effective_to'], name='provider_ro_effecti_e61a0c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('workspace', 'client', 'gstin', 'provider', 'return_type'), name='unique_active_provider_rollout_policy_scope')],
            },
        ),
    ]
