# Generated by Django 6.0.5 on 2026-06-03 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0005_providerrolloutpolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnFilingIncidentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=160)),
                ('note', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('alert_code', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filing_incident_notes_resolved', to=settings.AUTH_USER_MODEL)),
                ('return_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_notes', to='filings.returnfiling')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'return_filing_incident_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['return_filing', 'status', 'severity'], name='return_fili_return__ccc4ae_idx'), models.Index(fields=['alert_code'], name='return_fili_alert_c_2f9e4b_idx'), models.Index(fields=['resolved_at'], name='return_fili_resolve_5f35ca_idx')],
            },
        ),
    ]
