# Generated by Django 6.0.5 on 2026-06-03 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('filings', '0006_returnfilingincidentnote'),
        ('gstins', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAlertRoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider', models.CharField(choices=[('whitebooks', 'WhiteBooks'), ('demo_gsp', 'Demo GSP')], default='whitebooks', max_length=32)),
                ('return_type', models.CharField(blank=True, choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B')], max_length=32)),
                ('alert_code', models.CharField(blank=True, max_length=64)),
                ('minimum_severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('target_role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('reviewer', 'Reviewer'), ('filer', 'Filer'), ('senior_ca', 'Senior CA'), ('viewer', 'Viewer')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_alert_routing_rules', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gstin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_alert_routing_rules', to='gstins.gstin')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_alert_routing_rules', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'operational_alert_routing_rules',
                'ordering': ['workspace_id', 'provider', 'target_role', '-created_at'],
                'indexes': [models.Index(fields=['workspace', 'provider', 'is_active'], name='operational_workspa_8cbd0c_idx'), models.Index(fields=['client', 'provider', 'is_active'], name='operational_client__bd363d_idx'), models.Index(fields=['gstin', 'provider', 'is_active'], name='operational_gstin_i_768791_idx'), models.Index(fields=['provider', 'return_type', 'is_active'], name='operational_provide_44d912_idx'), models.Index(fields=['alert_code', 'minimum_severity'], name='operational_alert_c_3b3911_idx'), models.Index(fields=['target_role', 'is_active'], name='operational_target__1739e0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('workspace', 'client', 'gstin', 'provider', 'return_type', 'alert_code', 'target_role'), name='unique_active_operational_alert_rule_scope')],
            },
        ),
    ]
