# Generated by Django 6.0.5 on 2026-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0007_operationalalertroutingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalalertroutingrule',
            name='return_type',
            field=models.CharField(blank=True, choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('gstr9', 'GSTR-9')], max_length=32),
        ),
        migrations.AlterField(
            model_name='providerrolloutpolicy',
            name='return_type',
            field=models.CharField(blank=True, choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('gstr9', 'GSTR-9')], max_length=32),
        ),
        migrations.AlterField(
            model_name='returnfiling',
            name='return_type',
            field=models.CharField(choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('gstr9', 'GSTR-9')], max_length=32),
        ),
    ]
