# Generated by Django 6.0.5 on 2026-06-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0008_alter_operationalalertroutingrule_return_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalalertroutingrule',
            name='return_type',
            field=models.CharField(blank=True, choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('gstr9', 'GSTR-9'), ('gstr9c', 'GSTR-9C')], max_length=32),
        ),
        migrations.AlterField(
            model_name='providerrolloutpolicy',
            name='return_type',
            field=models.CharField(blank=True, choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('gstr9', 'GSTR-9'), ('gstr9c', 'GSTR-9C')], max_length=32),
        ),
        migrations.AlterField(
            model_name='returnfiling',
            name='return_type',
            field=models.CharField(choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('gstr9', 'GSTR-9'), ('gstr9c', 'GSTR-9C')], max_length=32),
        ),
    ]
