# Generated by Django 6.0.5 on 2026-05-25 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnpreparation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnpreparation',
            name='arn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='returnpreparation',
            name='filed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnpreparation',
            name='filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnpreparation',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_prepared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnpreparation',
            name='return_type',
            field=models.CharField(choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B')], max_length=32),
        ),
        migrations.AlterField(
            model_name='returnpreparation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('ready_for_review', 'Ready for Review'), ('approved', 'Approved'), ('filed', 'Filed'), ('failed', 'Failed')], default='draft', max_length=32),
        ),
    ]
