# Generated by Django 6.0.5 on 2026-06-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returnpreparation_approved_by_returnpreparation_arn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnpreparation',
            name='blocking_reason',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='returnpreparation',
            name='is_blocked_by_stale_reconciliation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='returnpreparation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('ready_for_review', 'Ready for Review'), ('blocked_by_stale_reconciliation', 'Blocked by Stale Reconciliation'), ('approved', 'Approved'), ('filed', 'Filed'), ('failed', 'Failed')], default='draft', max_length=32),
        ),
    ]
