# Generated by Django 6.0.5 on 2026-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_returnpreparation_blocking_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpreparation',
            name='return_type',
            field=models.CharField(choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('gstr9', 'GSTR-9')], max_length=32),
        ),
    ]
