# Generated by Django 6.0.5 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0004_alter_returnpreparation_return_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnpreparation",
            name="return_type",
            field=models.CharField(
                choices=[
                    ("gstr1", "GSTR-1"),
                    ("gstr3b", "GSTR-3B"),
                    ("gstr9", "GSTR-9"),
                    ("gstr9c", "GSTR-9C"),
                ],
                max_length=32,
            ),
        ),
    ]
