# Generated by Django 6.0.5 on 2026-06-07 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_periods', '0002_complianceperiod_is_locked_and_more'),
        ('filings', '0010_alter_operationalalertroutingrule_return_type_and_more'),
        ('returns', '0006_alter_returnpreparation_return_type_gstr7'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalLedgerSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider', models.CharField(default='whitebooks', max_length=32)),
                ('return_type', models.CharField(choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('gstr7', 'GSTR-7'), ('gstr9', 'GSTR-9'), ('gstr9c', 'GSTR-9C')], max_length=32)),
                ('fetched_at', models.DateTimeField()),
                ('computed_summary', models.JSONField(blank=True, default=dict)),
                ('balance_response', models.JSONField(blank=True, default=dict)),
                ('taxpayable_response', models.JSONField(blank=True, default=dict)),
                ('challan_reference', models.CharField(blank=True, max_length=64)),
                ('challan_history_response', models.JSONField(blank=True, default=dict)),
                ('challan_summary_response', models.JSONField(blank=True, default=dict)),
                ('auth_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_ledger_snapshots', to='filings.whitebooksauthsession')),
                ('compliance_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_ledger_snapshots', to='compliance_periods.complianceperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('prepared_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_ledger_snapshots', to='returns.returnpreparation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_ledger_snapshots',
                'ordering': ['-fetched_at', '-created_at'],
                'indexes': [models.Index(fields=['compliance_period', 'return_type', 'provider'], name='portal_ledg_complia_0b80c5_idx'), models.Index(fields=['auth_session', 'provider'], name='portal_ledg_auth_se_09cb7c_idx'), models.Index(fields=['fetched_at'], name='portal_ledg_fetched_9b2729_idx')],
            },
        ),
    ]
