# Generated by Django 6.0.5 on 2026-06-08 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_periods', '0002_complianceperiod_is_locked_and_more'),
        ('filings', '0010_alter_operationalalertroutingrule_return_type_and_more'),
        ('returns', '0007_portalledgersnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalChallanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider', models.CharField(default='whitebooks', max_length=32)),
                ('return_type', models.CharField(choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('gstr7', 'GSTR-7'), ('gstr9', 'GSTR-9'), ('gstr9c', 'GSTR-9C')], max_length=32)),
                ('status', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='created', max_length=32)),
                ('cpin', models.CharField(blank=True, max_length=64)),
                ('challan_reason', models.CharField(max_length=32)),
                ('challan_period', models.CharField(max_length=16)),
                ('payment_mode', models.CharField(max_length=16)),
                ('bank_code', models.CharField(blank=True, max_length=16)),
                ('sub_payment_mode', models.CharField(blank=True, max_length=16)),
                ('taxpayer_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=32)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('error_message', models.TextField(blank=True)),
                ('auth_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_challan_requests', to='filings.whitebooksauthsession')),
                ('compliance_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_challan_requests', to='compliance_periods.complianceperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('prepared_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_challan_requests', to='returns.returnpreparation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_challan_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['compliance_period', 'return_type', 'provider'], name='portal_chal_complia_826f98_idx'), models.Index(fields=['status', 'provider'], name='portal_chal_status_250f57_idx'), models.Index(fields=['cpin'], name='portal_chal_cpin_a8cdae_idx')],
            },
        ),
    ]
