# Generated by Django 5.0.6 on 2026-08-30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance_periods", "0002_complianceperiod_is_locked_and_more"),
        ("filings", "0010_alter_operationalalertroutingrule_return_type_and_more"),
        ("returns", "0010_portalledgersnapshot_itc_and_liability_responses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderReturnSummarySnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("provider", models.CharField(default="whitebooks", max_length=32)),
                (
                    "return_type",
                    models.CharField(
                        choices=[
                            ("gstr1", "GSTR-1"),
                            ("gstr3b", "GSTR-3B"),
                            ("gstr7", "GSTR-7"),
                            ("gstr9", "GSTR-9"),
                            ("gstr9c", "GSTR-9C"),
                        ],
                        max_length=32,
                    ),
                ),
                ("fetched_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("within_threshold", "Within Threshold"),
                            ("mismatch", "Mismatch"),
                            ("provider_unavailable", "Provider Unavailable"),
                            ("not_prepared", "Not Prepared"),
                        ],
                        max_length=32,
                    ),
                ),
                ("threshold_amount", models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ("internal_summary", models.JSONField(blank=True, default=dict)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("normalized_provider_summary", models.JSONField(blank=True, default=dict)),
                ("comparison_summary", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "auth_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_return_summary_snapshots",
                        to="filings.whitebooksauthsession",
                    ),
                ),
                (
                    "compliance_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_return_summary_snapshots",
                        to="compliance_periods.complianceperiod",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_return",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_return_summary_snapshots",
                        to="returns.returnpreparation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "provider_return_summary_snapshots",
                "ordering": ["-fetched_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="providerreturnsummarysnapshot",
            index=models.Index(fields=["compliance_period", "return_type", "provider"], name="provider_re_complia_8cf123_idx"),
        ),
        migrations.AddIndex(
            model_name="providerreturnsummarysnapshot",
            index=models.Index(fields=["status", "provider"], name="provider_re_status_6f896a_idx"),
        ),
        migrations.AddIndex(
            model_name="providerreturnsummarysnapshot",
            index=models.Index(fields=["fetched_at"], name="provider_re_fetched_908a4d_idx"),
        ),
    ]
