# Generated by Django 6.0.5 on 2026-06-05 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_clientcontact'),
        ('compliance_periods', '0002_complianceperiod_is_locked_and_more'),
        ('filings', '0007_operationalalertroutingrule'),
        ('gstins', '0003_gstintaxpayerprofile'),
        ('notices', '0002_notice_assigned_to_notice_due_date_and_more'),
        ('returns', '0003_returnpreparation_blocking_reason_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('contact_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('mobile_number_snapshot', models.CharField(blank=True, max_length=32)),
                ('email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('follow_up_type', models.CharField(choices=[('data_request', 'Data Request'), ('approval_request', 'Approval Request'), ('otp_coordination', 'OTP Coordination'), ('payment_confirmation', 'Payment Confirmation'), ('notice_document_request', 'Notice Document Request'), ('return_filing_confirmation', 'Return Filing Confirmation'), ('mismatch_resolution', 'Mismatch Resolution'), ('general', 'General')], default='general', max_length=32)),
                ('reason', models.CharField(max_length=255)),
                ('pending_with', models.CharField(choices=[('customer', 'Customer'), ('ca_team', 'CA Team'), ('reviewer', 'Reviewer'), ('provider', 'Provider'), ('government_portal', 'Government Portal')], default='customer', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('escalated', 'Escalated')], default='open', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_follow_ups_assigned', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_follow_ups', to='clients.client')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_follow_ups_completed', to=settings.AUTH_USER_MODEL)),
                ('compliance_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_follow_ups', to='compliance_periods.complianceperiod')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_follow_ups', to='clients.clientcontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gstin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_follow_ups', to='gstins.gstin')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_follow_ups', to='notices.notice')),
                ('return_filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_follow_ups', to='filings.returnfiling')),
                ('return_preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_follow_ups', to='returns.returnpreparation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_follow_ups', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'operational_follow_ups',
                'ordering': ['due_at', '-priority', '-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='operational_workspa_5bd6db_idx'), models.Index(fields=['workspace', 'pending_with'], name='operational_workspa_a1fdc0_idx'), models.Index(fields=['client', 'status'], name='operational_client__633f8d_idx'), models.Index(fields=['gstin', 'status'], name='operational_gstin_i_10ec6c_idx'), models.Index(fields=['compliance_period', 'status'], name='operational_complia_7f4acc_idx'), models.Index(fields=['assigned_to', 'status'], name='operational_assigne_a31778_idx'), models.Index(fields=['priority', 'status'], name='operational_priorit_13c276_idx'), models.Index(fields=['due_at'], name='operational_due_at_36112e_idx')],
            },
        ),
    ]
