# Generated by Codex on 2026-08-30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_clientcontact"),
        ("filings", "0010_alter_operationalalertroutingrule_return_type_and_more"),
        ("gstins", "0004_allow_same_gstin_across_workspaces"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IMSActionBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("provider", models.CharField(choices=[("whitebooks", "WhiteBooks"), ("demo_gsp", "Demo GSP")], default="whitebooks", max_length=32)),
                ("action_type", models.CharField(choices=[("save", "Save"), ("reset", "Reset")], max_length=16)),
                ("ret_period", models.CharField(max_length=6)),
                ("status", models.CharField(choices=[("requested", "Requested"), ("submitted", "Submitted"), ("failed", "Failed")], default="requested", max_length=24)),
                ("provider_transaction_id", models.CharField(blank=True, max_length=128)),
                ("request_payload_hash", models.CharField(blank=True, max_length=128)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auth_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ims_action_batches",
                        to="filings.whitebooksauthsession",
                    ),
                ),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ims_action_batches", to="clients.client")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("gstin", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ims_action_batches", to="gstins.gstin")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ims_action_batches_requested", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ims_action_batches", to="workspaces.workspace")),
            ],
            options={
                "db_table": "ims_action_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="imsactionbatch",
            index=models.Index(fields=["workspace", "status"], name="ims_action__workspa_0f779d_idx"),
        ),
        migrations.AddIndex(
            model_name="imsactionbatch",
            index=models.Index(fields=["client", "status"], name="ims_action__client__8b41e1_idx"),
        ),
        migrations.AddIndex(
            model_name="imsactionbatch",
            index=models.Index(fields=["gstin", "ret_period"], name="ims_action__gstin_i_5dfbb6_idx"),
        ),
        migrations.AddIndex(
            model_name="imsactionbatch",
            index=models.Index(fields=["action_type", "status"], name="ims_action__action__20876a_idx"),
        ),
        migrations.AddIndex(
            model_name="imsactionbatch",
            index=models.Index(fields=["provider_transaction_id"], name="ims_action__provide_9b9e24_idx"),
        ),
    ]
