# Generated by Django 6.0.5 on 2026-05-25 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('clients', '0001_initial'),
        ('compliance_periods', '0001_initial'),
        ('gstins', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='approvalrequest',
            name='approval_re_return__7b4b95_idx',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='clients.client'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='compliance_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='compliance_periods.complianceperiod'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='entity_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('import_batch', 'Import Batch'), ('reconciliation_run', 'Reconciliation Run'), ('return_preparation', 'Return Preparation'), ('compliance_period', 'Compliance Period')], max_length=32),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='gstin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='gstins.gstin'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='resolution_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['workspace', 'status'], name='approval_re_workspa_ee08ce_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['client', 'status'], name='approval_re_client__69f6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['compliance_period', 'status'], name='approval_re_complia_ff0b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['entity_type', 'entity_id'], name='approval_re_entity__0c15c4_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requested_to', 'status'], name='approval_re_request_f927d4_idx'),
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='return_preparation',
        ),
    ]
