# Generated by Django 6.0.5 on 2026-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstin',
            name='whitebooks_gst_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
