# Generated by Django 6.0.5 on 2026-06-03 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstins', '0002_gstin_whitebooks_gst_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTINTaxpayerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('trade_name', models.CharField(blank=True, default='', max_length=255)),
                ('registration_type', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('constitution', models.CharField(blank=True, default='', max_length=128)),
                ('registration_date', models.CharField(blank=True, default='', max_length=32)),
                ('last_updated_date', models.CharField(blank=True, default='', max_length=32)),
                ('state_jurisdiction_code', models.CharField(blank=True, default='', max_length=64)),
                ('state_jurisdiction_name', models.CharField(blank=True, default='', max_length=255)),
                ('center_jurisdiction_code', models.CharField(blank=True, default='', max_length=64)),
                ('center_jurisdiction_name', models.CharField(blank=True, default='', max_length=255)),
                ('principal_address', models.JSONField(blank=True, default=dict)),
                ('additional_addresses', models.JSONField(blank=True, default=list)),
                ('nature_of_business', models.JSONField(blank=True, default=list)),
                ('einvoice_status', models.CharField(blank=True, default='', max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gstin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxpayer_profile', to='gstins.gstin')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gstin_taxpayer_profiles',
                'ordering': ['gstin__gstin'],
            },
        ),
    ]
