# Generated by Django 6.0.5 on 2026-05-25 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_periods', '0001_initial'),
        ('gstins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceperiod',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='complianceperiod',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complianceperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_compliance_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='complianceperiod',
            index=models.Index(fields=['is_locked'], name='compliance__is_lock_63cdcd_idx'),
        ),
    ]
