# Generated by Django 6.0.5 on 2026-05-25 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance_periods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('compliance_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='compliance_periods.complianceperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reconciliation_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_reference', models.CharField(max_length=64)),
                ('target_reference', models.CharField(blank=True, max_length=64)),
                ('match_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('mismatch', 'Mismatch')], default='pending', max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('reconciliation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reconciliation.reconciliationrun')),
            ],
            options={
                'db_table': 'reconciliation_items',
                'ordering': ['source_reference'],
            },
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['compliance_period', 'status'], name='reconciliat_complia_44c16e_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['reconciliation_run', 'match_status'], name='reconciliat_reconci_d3bebb_idx'),
        ),
    ]
