# Generated by Django 6.0.5 on 2026-05-25 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('compliance_periods', '0001_initial'),
        ('gst_transactions', '0002_alter_gsttransaction_options_and_more'),
        ('gstins', '0001_initial'),
        ('reconciliation', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconciliationitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='reconciliationitem',
            name='source_reference',
        ),
        migrations.RemoveField(
            model_name='reconciliationitem',
            name='target_reference',
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='action_status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('deferred', 'Deferred'), ('ignored', 'Ignored')], default='open', max_length=32),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_items_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='books_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_books_items', to='gst_transactions.gsttransaction'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='mismatch_reason',
            field=models.CharField(blank=True, choices=[('gstin_mismatch', 'GSTIN Mismatch'), ('document_number_mismatch', 'Document Number Mismatch'), ('date_mismatch', 'Date Mismatch'), ('taxable_value_mismatch', 'Taxable Value Mismatch'), ('tax_amount_mismatch', 'Tax Amount Mismatch'), ('total_amount_mismatch', 'Total Amount Mismatch'), ('duplicate_invoice', 'Duplicate Invoice'), ('missing_in_books', 'Missing in Books'), ('missing_in_portal', 'Missing in Portal')], max_length=64),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='portal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_portal_items', to='gst_transactions.gsttransaction'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='tax_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='taxable_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='total_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='clients.client'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='error_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='gstin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_runs', to='gstins.gstin'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='matched_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='mismatch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='missing_in_books_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='missing_in_portal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='partial_match_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='run_type',
            field=models.CharField(choices=[('gstr_2b_purchase', 'GSTR-2B Purchase')], default='gstr_2b_purchase', max_length=32),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='total_itc_at_risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='total_tax_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='reconciliationitem',
            name='match_status',
            field=models.CharField(choices=[('matched', 'Matched'), ('partial_match', 'Partial Match'), ('mismatch', 'Mismatch'), ('missing_in_books', 'Missing in Books'), ('missing_in_portal', 'Missing in Portal'), ('duplicate_in_books', 'Duplicate in Books'), ('duplicate_in_portal', 'Duplicate in Portal')], default='matched', max_length=32),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['reconciliation_run', 'action_status'], name='reconciliat_reconci_427651_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['assigned_to'], name='reconciliat_assigne_0fd385_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['mismatch_reason'], name='reconciliat_mismatc_7d31fe_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['workspace', 'status'], name='reconciliat_workspa_f7a423_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['client', 'status'], name='reconciliat_client__19d25e_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['run_type', 'status'], name='reconciliat_run_typ_d91ed1_idx'),
        ),
    ]
