# Generated by Django 6.0.5 on 2026-06-04 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_alter_reconciliationitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationitem',
            name='derived_from_stale_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='invalidated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_runs_invalidated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='invalidation_reason',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='is_stale',
            field=models.BooleanField(default=False),
        ),
    ]
