# Generated by Django 6.0.5 on 2026-06-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0003_reconciliationitem_derived_from_stale_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationitem",
            name="issue_bucket",
            field=models.CharField(
                choices=[
                    ("ready", "Ready / Matched"),
                    ("timing_difference", "Timing Difference"),
                    ("vendor_follow_up", "Vendor Follow-up"),
                    ("books_correction", "Books Correction"),
                    ("value_review", "Value Review"),
                    ("document_review", "Document Review"),
                    ("duplicate_cleanup", "Duplicate Cleanup"),
                    ("issue_review", "General Review"),
                ],
                default="issue_review",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationitem",
            name="period_relationship",
            field=models.CharField(
                choices=[
                    ("same_period", "Same Period"),
                    ("prior_period", "Prior Period"),
                    ("next_period", "Next Period"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationitem",
            name="recommended_next_action",
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddIndex(
            model_name="reconciliationitem",
            index=models.Index(fields=["reconciliation_run", "issue_bucket"], name="reconciliat_reconci_24d9d5_idx"),
        ),
    ]
