# Generated by Django 6.0.5 on 2026-06-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0004_reconciliationitem_decision_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reconciliationitem",
            new_name="reconciliat_reconci_9e3439_idx",
            old_name="reconciliat_reconci_24d9d5_idx",
        ),
    ]
