# Generated by Django 6.0.5 on 2026-06-05 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_transactions', '0010_transactionremediationfollowup_auto_escalated_at_and_more'),
        ('reconciliation', '0005_rename_reconciliat_reconci_24d9d5_idx_reconciliat_reconci_9e3439_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationitem',
            name='itc_status',
            field=models.CharField(choices=[('itc_ready', 'ITC Ready'), ('itc_pending_2b', 'ITC Pending 2B'), ('itc_pending_review', 'ITC Pending Review'), ('itc_blocked', 'ITC Blocked'), ('itc_timing_difference', 'ITC Timing Difference'), ('itc_vendor_followup_required', 'ITC Vendor Follow-up Required')], default='itc_pending_review', max_length=40),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='itc_blocked_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='itc_pending_2b_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='itc_pending_review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='itc_ready_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='itc_timing_difference_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='itc_vendor_followup_required_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['reconciliation_run', 'itc_status'], name='reconciliat_reconci_d8b3d9_idx'),
        ),
    ]
