# Generated by Django 6.0.5 on 2026-06-06 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_transactions', '0012_alter_transactioncorrection_correction_scope'),
        ('reconciliation', '0006_reconciliationitem_itc_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationitem',
            name='review_decision',
            field=models.CharField(choices=[('auto', 'Auto'), ('claim_now', 'Claim Now'), ('defer', 'Defer'), ('blocked', 'Blocked'), ('vendor_follow_up', 'Vendor Follow-up')], default='auto', max_length=24),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['reconciliation_run', 'review_decision'], name='reconciliat_reconci_ef2f3b_idx'),
        ),
    ]
