# Generated by Django 6.0.5 on 2026-06-05 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=128)),
                ('mobile_number', models.CharField(blank=True, max_length=32)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('preferred_contact_mode', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='call', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_contacts',
                'ordering': ['-is_primary', 'name'],
                'indexes': [models.Index(fields=['client', 'is_primary'], name='client_cont_client__6d1ddb_idx'), models.Index(fields=['mobile_number'], name='client_cont_mobile__094023_idx'), models.Index(fields=['email'], name='client_cont_email_c09782_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('client',), name='unique_active_primary_contact_per_client')],
            },
        ),
    ]
