# Generated by Django 6.0.5 on 2026-05-25 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('compliance_periods', '0001_initial'),
        ('gst_transactions', '0001_initial'),
        ('gstins', '0001_initial'),
        ('imports', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gsttransaction',
            options={'ordering': ['-transaction_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_transactions', to='clients.client'),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='compliance_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_transactions', to='compliance_periods.complianceperiod'),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='counterparty_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='counterparty_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='document_type',
            field=models.CharField(default='invoice', max_length=32),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='gstin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_transactions', to='gstins.gstin'),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('review', 'Review'), ('locked', 'Locked')], default='imported', max_length=32),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_transactions', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='gsttransaction',
            index=models.Index(fields=['workspace', 'client', 'transaction_date'], name='gst_transac_workspa_61f958_idx'),
        ),
        migrations.AddIndex(
            model_name='gsttransaction',
            index=models.Index(fields=['gstin', 'compliance_period'], name='gst_transac_gstin_i_067351_idx'),
        ),
        migrations.AddIndex(
            model_name='gsttransaction',
            index=models.Index(fields=['import_batch'], name='gst_transac_import__4469f3_idx'),
        ),
    ]
