# Generated by Django 6.0.5 on 2026-05-26 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('compliance_periods', '0002_complianceperiod_is_locked_and_more'),
        ('gst_transactions', '0003_transactionreviewsnapshot'),
        ('gstins', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRemediationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bucket_code', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('transaction_ids', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('deferred', 'Deferred')], default='open', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_remediation_assignments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_remediation_assignments', to='clients.client')),
                ('compliance_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_remediation_assignments', to='compliance_periods.complianceperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gstin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_remediation_assignments', to='gstins.gstin')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='gst_transactions.transactionreviewsnapshot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_remediation_assignments', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'transaction_remediation_assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'client', 'status'], name='transaction_workspa_9daa40_idx'), models.Index(fields=['compliance_period', 'status'], name='transaction_complia_5dd217_idx'), models.Index(fields=['assigned_to', 'status'], name='transaction_assigne_366d0f_idx'), models.Index(fields=['bucket_code'], name='transaction_bucket__faee18_idx')],
            },
        ),
    ]
