# Generated by Django 6.0.5 on 2026-05-26 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('compliance_periods', '0002_complianceperiod_is_locked_and_more'),
        ('gst_transactions', '0004_transactionremediationassignment'),
        ('gstins', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionremediationassignment',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionremediationassignment',
            name='escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_remediation_assignments_escalated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionremediationassignment',
            name='escalation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='transactionremediationassignment',
            index=models.Index(fields=['escalated_at'], name='transaction_escalat_6a6558_idx'),
        ),
    ]
