# Generated by Django 6.0.5 on 2026-05-27 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('compliance_periods', '0002_complianceperiod_is_locked_and_more'),
        ('gst_transactions', '0005_transactionremediationassignment_escalated_at_and_more'),
        ('gstins', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRemediationFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('follow_up_type', models.CharField(choices=[('reminder', 'Reminder'), ('manager_review', 'Manager Review'), ('escalation_check', 'Escalation Check'), ('close_checkpoint', 'Close Checkpoint')], default='reminder', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('sent', 'Sent'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='open', max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('remind_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_remediation_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='gst_transactions.transactionremediationassignment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_remediation_follow_ups', to='clients.client')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_remediation_follow_ups_completed', to=settings.AUTH_USER_MODEL)),
                ('compliance_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_remediation_follow_ups', to='compliance_periods.complianceperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gstin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_remediation_follow_ups', to='gstins.gstin')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_remediation_follow_ups', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'transaction_remediation_follow_ups',
                'ordering': ['remind_at', '-created_at'],
                'indexes': [models.Index(fields=['workspace', 'client', 'status'], name='transaction_workspa_18bc3e_idx'), models.Index(fields=['compliance_period', 'status'], name='transaction_complia_d29468_idx'), models.Index(fields=['assignment', 'status'], name='transaction_assignm_e43df4_idx'), models.Index(fields=['assigned_to', 'status'], name='transaction_assigne_d23f23_idx'), models.Index(fields=['remind_at'], name='transaction_remind__41f0ab_idx')],
            },
        ),
    ]
