# Generated by Django 6.0.5 on 2026-05-27 03:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_transactions', '0006_transactionremediationfollowup'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRemediationDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=160)),
                ('delivery_channel', models.CharField(choices=[('in_app', 'In App'), ('email_preview', 'Email Preview')], default='in_app', max_length=32)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('acknowledged', 'Acknowledged')], default='generated', max_length=32)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_remediation_digests_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_remediation_digests_generated', to=settings.AUTH_USER_MODEL)),
                ('generated_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_remediation_digests_for', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_remediation_digests', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'transaction_remediation_digests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='transaction_workspa_20039b_idx'), models.Index(fields=['generated_for', 'status'], name='transaction_generat_d035ae_idx'), models.Index(fields=['delivery_channel'], name='transaction_deliver_54e2f3_idx')],
            },
        ),
    ]
