# Generated by Django 6.0.5 on 2026-05-27 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_transactions', '0007_transactionremediationdigest'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionremediationdigest',
            name='dispatch_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transactionremediationdigest',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionremediationdigest',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_remediation_digests_dispatched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionremediationdigest',
            name='rendered_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transactionremediationdigest',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('dispatched', 'Dispatched'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='generated', max_length=32),
        ),
        migrations.AddIndex(
            model_name='transactionremediationdigest',
            index=models.Index(fields=['dispatched_at'], name='transaction_dispatc_9bc999_idx'),
        ),
    ]
