# Generated by Django 6.0.5 on 2026-05-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_transactions', '0008_transactionremediationdigest_dispatch_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionremediationdigest',
            name='delivery_channel',
            field=models.CharField(choices=[('in_app', 'In App'), ('email_preview', 'Email Preview'), ('email', 'Email')], default='in_app', max_length=32),
        ),
    ]
