# Generated by Django 6.0.5 on 2026-05-27 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('compliance_periods', '0002_complianceperiod_is_locked_and_more'),
        ('gst_transactions', '0009_alter_transactionremediationdigest_delivery_channel'),
        ('gstins', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionremediationfollowup',
            name='auto_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionremediationfollowup',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionremediationfollowup',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='transactionremediationfollowup',
            index=models.Index(fields=['last_notified_at'], name='transaction_last_no_05f744_idx'),
        ),
    ]
