# Generated by Django 6.0.5 on 2026-06-06 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientcontact'),
        ('compliance_periods', '0002_complianceperiod_is_locked_and_more'),
        ('gst_transactions', '0010_transactionremediationfollowup_auto_escalated_at_and_more'),
        ('gstins', '0004_allow_same_gstin_across_workspaces'),
        ('reconciliation', '0006_reconciliationitem_itc_status_and_more'),
        ('workspaces', '0002_workspace_office_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('correction_scope', models.CharField(choices=[('reconciliation_books', 'Reconciliation Books Correction')], default='reconciliation_books', max_length=48)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reverted', 'Reverted')], default='applied', max_length=24)),
                ('reason_code', models.CharField(max_length=64)),
                ('reason_note', models.TextField(blank=True)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField()),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('revert_reason', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_corrections_applied', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_corrections', to='clients.client')),
                ('compliance_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_corrections', to='compliance_periods.complianceperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gstin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_corrections', to='gstins.gstin')),
                ('reconciliation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_corrections', to='reconciliation.reconciliationitem')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_corrections_reverted', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='gst_transactions.gsttransaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_corrections', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'transaction_corrections',
                'ordering': ['-applied_at', '-created_at'],
                'indexes': [models.Index(fields=['workspace', 'client', 'applied_at'], name='transaction_workspa_99a76c_idx'), models.Index(fields=['compliance_period', 'applied_at'], name='transaction_complia_70d71c_idx'), models.Index(fields=['transaction', 'applied_at'], name='transaction_transac_9dde78_idx'), models.Index(fields=['reconciliation_item', 'applied_at'], name='transaction_reconci_83f868_idx'), models.Index(fields=['status'], name='transaction_status_71e6ca_idx'), models.Index(fields=['reason_code'], name='transaction_reason__72cd8b_idx')],
            },
        ),
    ]
