# Generated by Django 6.0.5 on 2026-06-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_transactions', '0011_transactioncorrection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncorrection',
            name='correction_scope',
            field=models.CharField(choices=[('reconciliation_books', 'Reconciliation Books Correction'), ('reconciliation_books_create', 'Reconciliation Books Entry Creation')], default='reconciliation_books', max_length=48),
        ),
    ]
