# Generated by Django 6.0.5 on 2026-05-25 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('compliance_periods', '0001_initial'),
        ('gstins', '0001_initial'),
        ('imports', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='importbatch',
            name='import_batc_source__0cd90d_idx',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='clients.client'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='error_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='import_batches/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='gstin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='gstins.gstin'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('gstr_2b', 'GSTR-2B')], default='sales', max_length=32),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='invalid_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='valid_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='importrowerror',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importrowerror',
            name='raw_row',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrowerror',
            name='severity',
            field=models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], default='error', max_length=16),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source_type',
            field=models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV')], max_length=16),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=32),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['workspace', 'status'], name='import_batc_workspa_d242a8_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['client', 'status'], name='import_batc_client__13a90d_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['import_type', 'source_type'], name='import_batc_import__bdd984_idx'),
        ),
        migrations.AddIndex(
            model_name='importrowerror',
            index=models.Index(fields=['import_batch', 'severity'], name='import_row__import__55a575_idx'),
        ),
    ]
