# Generated by Django 6.0.5 on 2026-05-25 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_remove_importbatch_import_batc_source__0cd90d_idx_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('import_type', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('gstr_2b', 'GSTR-2B')], max_length=32)),
                ('source_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV')], max_length=16)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_templates', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'import_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='importbatch',
            name='import_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='imports.importtemplate'),
        ),
        migrations.AddIndex(
            model_name='importtemplate',
            index=models.Index(fields=['workspace', 'import_type', 'source_type'], name='import_temp_workspa_4797de_idx'),
        ),
        migrations.AddIndex(
            model_name='importtemplate',
            index=models.Index(fields=['workspace', 'is_default'], name='import_temp_workspa_aa3f6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='importtemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'name', 'import_type', 'source_type'), name='unique_import_template_per_workspace_type'),
        ),
    ]
