# Generated by Django 6.0.5 on 2026-06-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importtemplate_importbatch_import_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='importtemplate',
            name='source_type',
            field=models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('provider', 'Provider')], max_length=16),
        ),
    ]
