# Generated by Django 6.0.5 on 2026-06-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_importbatch_source_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='source_type',
            field=models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('provider', 'Provider')], max_length=16),
        ),
    ]
