# Generated by Django 6.0.5 on 2026-06-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_importbatch_corrected_at_importbatch_corrected_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('advance_received', 'Advance Received'), ('advance_adjusted', 'Advance Adjusted'), ('gstr_2b', 'GSTR-2B')], default='sales', max_length=32),
        ),
        migrations.AlterField(
            model_name='importtemplate',
            name='import_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('advance_received', 'Advance Received'), ('advance_adjusted', 'Advance Adjusted'), ('gstr_2b', 'GSTR-2B')], max_length=32),
        ),
    ]
