# Generated by Django 6.0.5 on 2026-05-25 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='after_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='before_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='compliance_period_id_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='gstin_id_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['gstin_id_ref', 'action'], name='audit_logs_gstin_i_780a68_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['compliance_period_id_ref', 'action'], name='audit_logs_complia_42f844_idx'),
        ),
    ]
